---
apiVersion: openstack.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: provider-openstack-config
spec:
  credentials:
    source: Secret
    secretRef:
      key: config
      name: provider-openstack-config
      namespace: crossplane-system

