---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: provider-openstack-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: central
    kind: ClusterSecretStore
  target:
    name: provider-openstack-config
    template:
      data:
        config: '{"auth_url": "https://dashboard.bws.burda.com:5000","application_credential_id": "{{ .applicationCredentialId }}","application_credential_secret": "{{ .applicationCredentialSecret }}"}'
  data:
    - secretKey: applicationCredentialId
      remoteRef:
        key: cluster-secrets
        property: application_credential_id
    - secretKey: applicationCredentialSecret
      remoteRef:
        key: cluster-secrets
        property: application_credential_secret
